# ---
# Github action workflow for releasing the current version of the library
# ---

name: Release Pipeline
run-name: Releasing ${{ github.ref }} to Maven Central
on:
  push:
    tags:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup-java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      - name: Publish all artifacts
        env:
          OSSRH_USERNAME: ${{ secrets.NEXUS_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
          SIGNING_KEY: ${{ secrets.GPG_KEY }}
          SIGNING_PASSWORD: ${{ secrets.GPG_PASSWORD }}
          ENABLE_PUBLISHING: true
          PUBLISH_RELEASE: true
        run: ./gradlew publishAllPublicationsToSonatypeRepository --stacktrace

      - name: Archive artifacts
        uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: |
            **/build/libs
            **/build/outputs