# ---
# Github action workflow for releasing the current version of the library
# ---

name: Trunk Pipeline
run-name: Build
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup-java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      - name: Build with Gradle
        ## For now run only JVM part since iOS has a problem on linking process
        run: ./gradlew :shared:assembleDebug

      - name: Archive artifacts
        uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: |
            **/build/libs
            **/build/outputs
